//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesGenerator.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames_Custom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames_Custom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntitiesGenerator.Mvc.DisplayNames_Custom", typeof(DisplayNames_Custom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Model.
        /// </summary>
        public static string AbstractModel {
            get {
                return ResourceManager.GetString("AbstractModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Property Name.
        /// </summary>
        public static string CodePropertyName {
            get {
                return ResourceManager.GetString("CodePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Restrict.
        /// </summary>
        public static string DeleteRestrict {
            get {
                return ResourceManager.GetString("DeleteRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Location.
        /// </summary>
        public static string GenerateLocation {
            get {
                return ResourceManager.GetString("GenerateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has AspNetCore Options.
        /// </summary>
        public static string HasAspNetCoreOptions {
            get {
                return ResourceManager.GetString("HasAspNetCoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Code Generator.
        /// </summary>
        public static string HasCodeGenerator {
            get {
                return ResourceManager.GetString("HasCodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Core Options.
        /// </summary>
        public static string HasCoreOptions {
            get {
                return ResourceManager.GetString("HasCoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has EntityFrameworkCore.SealedModels Options.
        /// </summary>
        public static string HasEntityFrameworkCoreSealedModelsOptions {
            get {
                return ResourceManager.GetString("HasEntityFrameworkCoreSealedModelsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Full Children in Parent View Model.
        /// </summary>
        public static string HasFullChildrenInParentViewModel {
            get {
                return ResourceManager.GetString("HasFullChildrenInParentViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Full Item 1s in Item 2 View Model.
        /// </summary>
        public static string HasFullItem1sInItem2ViewModel {
            get {
                return ResourceManager.GetString("HasFullItem1sInItem2ViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Full Item 2s in Item 1 View Model.
        /// </summary>
        public static string HasFullItem2sInItem1ViewModel {
            get {
                return ResourceManager.GetString("HasFullItem2sInItem1ViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Full Parent in Children View Model.
        /// </summary>
        public static string HasFullParentInChildrenViewModel {
            get {
                return ResourceManager.GetString("HasFullParentInChildrenViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Own Namespace.
        /// </summary>
        public static string HasOwnNamespace {
            get {
                return ResourceManager.GetString("HasOwnNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Sorted Children in Parent.
        /// </summary>
        public static string HasSortedChildrenInParent {
            get {
                return ResourceManager.GetString("HasSortedChildrenInParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Sorted Item 1s in Item 2.
        /// </summary>
        public static string HasSortedItem1sInItem2 {
            get {
                return ResourceManager.GetString("HasSortedItem1sInItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Sorted Item 2s in Item 1.
        /// </summary>
        public static string HasSortedItem2sInItem1 {
            get {
                return ResourceManager.GetString("HasSortedItem2sInItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Source Property Name.
        /// </summary>
        public static string IdSourcePropertyName {
            get {
                return ResourceManager.GetString("IdSourcePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Custom Display Names.
        /// </summary>
        public static string IncludeCustomDisplayNames {
            get {
                return ResourceManager.GetString("IncludeCustomDisplayNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1 Property Name.
        /// </summary>
        public static string Item1PropertyName {
            get {
                return ResourceManager.GetString("Item1PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2 Property Name.
        /// </summary>
        public static string Item2PropertyName {
            get {
                return ResourceManager.GetString("Item2PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Normalizer.
        /// </summary>
        public static string LookupNormalizer {
            get {
                return ResourceManager.GetString("LookupNormalizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Only.
        /// </summary>
        public static string ModelOnly {
            get {
                return ResourceManager.GetString("ModelOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Property Name.
        /// </summary>
        public static string NamePropertyName {
            get {
                return ResourceManager.GetString("NamePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter List Line Break.
        /// </summary>
        public static string ParameterListLineBreak {
            get {
                return ResourceManager.GetString("ParameterListLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        public static string ParentName {
            get {
                return ResourceManager.GetString("ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Nullable.
        /// </summary>
        public static string ParentNullable {
            get {
                return ResourceManager.GetString("ParentNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Mapping Lite View Model.
        /// </summary>
        public static string ReverseMappingLiteViewModel {
            get {
                return ResourceManager.GetString("ReverseMappingLiteViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope Name.
        /// </summary>
        public static string ScopeName {
            get {
                return ResourceManager.GetString("ScopeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted Children in Parent Criteria Property Name.
        /// </summary>
        public static string SortedChildrenInParentCriteriaPropertyName {
            get {
                return ResourceManager.GetString("SortedChildrenInParentCriteriaPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted Item 1s in Item 2 Criteria Property Name.
        /// </summary>
        public static string SortedItem1sInItem2CriteriaPropertyName {
            get {
                return ResourceManager.GetString("SortedItem1sInItem2CriteriaPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted Item 2s in Item 1 Criteria Property Name.
        /// </summary>
        public static string SortedItem2sInItem1CriteriaPropertyName {
            get {
                return ResourceManager.GetString("SortedItem2sInItem1CriteriaPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Active Field.
        /// </summary>
        public static string UseActiveField {
            get {
                return ResourceManager.GetString("UseActiveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Location.
        /// </summary>
        public static string WorkingLocation {
            get {
                return ResourceManager.GetString("WorkingLocation", resourceCulture);
            }
        }
    }
}
