//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesGenerator.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames_Custom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames_Custom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntitiesGenerator.Mvc.DisplayNames.Custom", typeof(DisplayNames_Custom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Model.
        /// </summary>
        public static string AbstractModel {
            get {
                return ResourceManager.GetString("AbstractModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Restrict.
        /// </summary>
        public static string DeleteRestrict {
            get {
                return ResourceManager.GetString("DeleteRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Settings.
        /// </summary>
        public static string FeatureSettings {
            get {
                return ResourceManager.GetString("FeatureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Location.
        /// </summary>
        public static string GenerateLocation {
            get {
                return ResourceManager.GetString("GenerateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Code Generator.
        /// </summary>
        public static string HasCodeGenerator {
            get {
                return ResourceManager.GetString("HasCodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Own Namespace.
        /// </summary>
        public static string HasOwnNamespace {
            get {
                return ResourceManager.GetString("HasOwnNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Sorted Children in Scope.
        /// </summary>
        public static string HasSortedChildrenInScope {
            get {
                return ResourceManager.GetString("HasSortedChildrenInScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Source Property Name.
        /// </summary>
        public static string IdSourcePropertyName {
            get {
                return ResourceManager.GetString("IdSourcePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1.
        /// </summary>
        public static string Item1 {
            get {
                return ResourceManager.GetString("Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2.
        /// </summary>
        public static string Item2 {
            get {
                return ResourceManager.GetString("Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter List Line Break.
        /// </summary>
        public static string ParameterListLineBreak {
            get {
                return ResourceManager.GetString("ParameterListLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope Name.
        /// </summary>
        public static string ScopeName {
            get {
                return ResourceManager.GetString("ScopeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted Children in Scope Criteria Property Name.
        /// </summary>
        public static string SortedChildrenInScopeCriteriaPropertyName {
            get {
                return ResourceManager.GetString("SortedChildrenInScopeCriteriaPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Location.
        /// </summary>
        public static string WorkingLocation {
            get {
                return ResourceManager.GetString("WorkingLocation", resourceCulture);
            }
        }
    }
}
